/* trace_commons.h -- C ABI for the trace-commons-contributor background
 * daemon.
 *
 * This is the surface a native application shell (SwiftUI on macOS, WinUI
 * on Windows, GTK on Linux) links against to host the daemon loop
 * in-process instead of shipping a second signed binary. It is generated by
 * hand to match `crates/trace-commons-contributor-ffi/src/lib.rs`
 * (`#[unsafe(no_mangle)] pub unsafe extern "C" fn ...`) exactly; keep the
 * two in sync when either changes.
 *
 * OWNERSHIP RULE, stated once, enforced everywhere in this header: every
 * `char*` RETURNED by this library is owned by the caller and freed with
 * `tc_string_free`. Every `const char*` is BORROWED and valid only until
 * the handle that owns it (`tc_handle*` or `tc_preview*`) is freed. There
 * is no other lifetime rule anywhere in this API.
 *
 * tc_daemon_start returns a tc_handle*; tc_daemon_stop tears the running
 * daemon down but does NOT free that pointer -- a concurrent tc_call /
 * tc_preview_open / tc_subscribe on another thread stays valid and simply
 * observes the daemon as stopped, rather than dereferencing freed memory.
 * tc_handle_free is the only function that reclaims it, and -- like every
 * free function here -- must not be called concurrently with any other
 * call still using the same pointer, and must be called from a plain
 * thread, never from inside a tc_subscribe callback (see its own doc for
 * why). In particular, tc_handle_free must NOT be called concurrently with
 * tc_daemon_stop: tc_daemon_stop does not free the handle, but it also does
 * not hold it against a concurrent free, and tc_handle_free performs its own
 * teardown before freeing.
 *
 * tc_daemon_stop is idempotent, but it is NOT a teardown barrier for a
 * SECOND CONCURRENT CALLER. If two threads call it at once, one thread
 * performs the teardown and blocks until it completes; the other returns
 * IMMEDIATELY, possibly while the daemon is still stopping. Do not treat a
 * tc_daemon_stop return on thread B as proof that thread A's teardown
 * finished. (An earlier revision made the second caller wait; that was
 * unsound -- if the winning caller was tc_handle_free it freed the very lock
 * the waiter had to re-acquire, and a waiter parked on one of the daemon
 * runtime's own worker threads could deadlock the teardown it was waiting
 * for. A weaker honest guarantee is better than a stronger false one.)
 *
 * Every function here catches Rust panics at the boundary and converts them
 * to an ordinary error; a panic never unwinds into the caller. Every
 * pointer parameter is null-checked; passing NULL produces an error, not a
 * crash. No path, token, URL, or trace content ever appears in a string
 * this library returns -- fixed labels only, the same discipline the
 * daemon's socket already applies.
 *
 * THREE NAMED EXEMPTIONS, and no others: tc_discover_sources returns
 * filesystem paths, tc_preview_body returns post-redaction trace content,
 * and tc_witness_status_json returns the witness URL and signing address.
 * Each is documented where it is declared, and each is a value the
 * contributor is being asked to make a decision about -- a consent prompt
 * that will not name what it is asking about is not a consent prompt.
 *
 * THE PREVIEW EXEMPTION: tc_preview_body is the one and only interface here
 * that deliberately carries trace content, and the rule above is absolute
 * everywhere else. A contributor cannot consent to sending something they
 * cannot see, so the exemption exists -- bounded to post-redaction content
 * only, only for an entry the caller already opened a preview for, and
 * never in a log line, an audit entry, a history record, notification text,
 * or a receipt. Preview content fails outright, rather than being silently
 * edited, if it cannot be represented as a NUL-terminated C string.
 *
 * One narrow addition: tc_search_original answers a yes/no-with-a-number
 * question about PRE-redaction content. It returns a count and never a
 * byte, for a needle the caller supplied, on an entry they already hold.
 *
 * Opening a preview also stores the redacted envelope it built in the
 * contributor's own private state directory (0600, one file per previewed
 * entry, deleted when the entry resolves and on logout), so the upload can
 * send exactly the bytes that were shown. Those stored bytes never come
 * back across this ABI.
 *
 * Every free function (tc_handle_free, tc_preview_free, tc_string_free)
 * detects a double free or a pointer of the wrong kind (e.g. a tc_handle*
 * passed to tc_preview_free) and refuses rather than acting on it --
 * recording a fixed label via tc_last_error and leaking the pointer, which
 * is the only safe response once a raw pointer's type cannot be trusted.
 *
 * The tc_preview_* ACCESSORS run that same check before they dereference:
 * a pointer that is not currently a live tc_preview* yields NULL (or -1
 * from tc_preview_search) plus the fixed tc_last_error label
 * "invalid-preview-pointer", rather than reading freed or wrongly-typed
 * memory. Be clear on the limits of that check: it is keyed on the pointer
 * VALUE, not on shared ownership of the allocation. It cannot make a
 * concurrent tc_preview_free safe -- the object can be freed between the
 * check and the read -- and a freed address later reused by another
 * tc_preview allocation will pass it. Do not free a tc_preview* while
 * another thread is inside an accessor for it; the check narrows accidental
 * misuse to a clean error, it does not replace ownership discipline.
 *
 * The six functions that borrow rather than free a tc_handle* --
 * tc_daemon_stop, tc_call, tc_subscribe, tc_unsubscribe, tc_preview_open,
 * and tc_preview_turns_json -- run the same shape of check on handle
 * before they dereference it: a pointer that is not currently a live
 * tc_handle* (already freed by tc_handle_free, or a tc_preview* passed
 * here by mistake) is refused with the fixed tc_last_error label
 * "invalid-handle-pointer", using whichever failure return that function
 * already had for a NULL handle -- see each function's own comment below
 * for the exact value. The same limits apply: keyed on the pointer VALUE,
 * not on shared ownership; it cannot make a concurrent tc_handle_free
 * safe, and a freed address later reused by a new tc_daemon_start will
 * pass it.
 *
 * SUBSCRIPTION LIFETIME: tc_daemon_stop does NOT end a subscription and is
 * NOT a synchronization point for one -- it only sets a flag a
 * subscription's background task polls at most every 250ms, and an event
 * already buffered when tc_daemon_stop was called can still be delivered in
 * that window. A tc_subscribe callback can be invoked, using ctx, well
 * after tc_daemon_stop has returned to its caller. tc_unsubscribe is the
 * ONLY function that guarantees no further callback invocation once it
 * returns; ctx must remain valid until tc_unsubscribe returns, full stop.
 */

#ifndef TRACE_COMMONS_H
#define TRACE_COMMONS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Opaque handle to a running daemon, returned by tc_daemon_start. */
typedef struct tc_handle tc_handle;

/* Independent compute controller, one per app, with no trace enrollment needed.
 * Open restores consent as paused and never starts a worker. Production open
 * has no packaged backend: available/can_enable/can_resume/can_pause are false.
 * Status/command return owned JSON strings (tc_string_free), or NULL with a
 * fixed tc_last_error label. Open errors use the owned err output. Commands
 * serialize settings I/O and must run off the UI thread. command_json is a
 * NUL-terminated string of at most 4096 bytes: {"command":"enable",
 * "ram_allowance_gib":8}, or {"command":"resume"|"pause"|"disable"}.
 * Unknown fields are refused. Never free concurrently with another handle call.
 * Free refuses to release a local handle with pending work or unconfirmed stop
 * (tc_last_error=compute-worker-still-owned). Shut down and retry after confirmed
 * worker_stopped=true and command_pending=false. Free never drains synchronously. */
typedef struct tc_compute_handle tc_compute_handle;
tc_compute_handle *tc_compute_open(const char *config_dir, char **err);
char *tc_compute_status_json(tc_compute_handle *handle);
/* Native resource ingress: obtain a single-use {epoch,sequence} ticket BEFORE
 * reading every field. Submit {event:"sample",ticket:{epoch,sequence},reading:
 * {power,low_power_mode,thermal,memory}}, or {event:"sleep"}/{event:"wake"}.
 * Snake-case enum strings; low_power_mode is bool/null. JSON <=4096 bytes.
 * NULL for unavailable/refused; owned strings use tc_string_free. Short calls
 * may run concurrently with shutdown, but NEVER with free. No launch authority. */
char *tc_compute_resource_begin_json(tc_compute_handle *handle);
char *tc_compute_resource_event_json(tc_compute_handle *handle, const char *json);
char *tc_compute_command_json(tc_compute_handle *handle, const char *command_json);
void tc_compute_free(tc_compute_handle *handle);
/* Shared copy independent of handle; returned JSON is caller-owned. */
char *tc_compute_copy_json(void);
/* Background-thread stop; wait clamped to 30 seconds. Keep handle if returned
 * worker_stopped is false. drain_outcome is separate coordinator evidence. */
char *tc_compute_shutdown(tc_compute_handle *handle, uint64_t timeout_ms);
/* Shutdown is terminal; starts are refused afterward. Retain/retry shutdown on
 * unconfirmed exit; reopen only after worker_stopped=true to restore paused.
 * Explicit Unix DEBUG development constructor; always refused in release.
 * Strict <=4096-byte config JSON: binary, expected_sha256, coordinator,
 * startup_timeout_secs. Absolute binary and loopback coordinator required.
 * No worker launch until explicit consent. Not called by the production open. */
tc_compute_handle *tc_compute_open_local(const char *config_dir, const char *local_config_json, char **err);

/* Opaque handle to one open preview, returned by tc_preview_open. */
typedef struct tc_preview tc_preview;

/* Lifecycle. Runs the daemon loop on its own thread with its own runtime.
 *
 * Returns NULL and sets *err (if err is non-NULL) on failure -- most
 * notably when another daemon already holds daemon.lock for this
 * config_dir. A second tc_daemon_start against the same directory must
 * fail rather than let two loops race the same on-disk queue. *err, on
 * failure, is an owned string; free it with tc_string_free.
 *
 * The daemon's runtime is sized at no fewer than two worker threads, and
 * that floor overrides TOKIO_WORKER_THREADS. It is not a tuning choice: at
 * one worker, an in-flight tc_subscribe callback and tc_daemon_stop's join
 * on the supervisor are mutually exclusive demands on the only worker, and
 * tc_daemon_stop is documented as callable from inside a callback.
 *
 * FAILS CLOSED ON UNDECLARED SESSION ROOTS. If the persisted settings do
 * not declare BOTH claude_root and codex_root, this returns NULL with the
 * fixed label "roots-not-declared" and nothing is scanned. An unset root
 * does not mean "no source for that agent" -- it means the conventional
 * per-user location, i.e. the contributor's real ~/.claude or ~/.codex --
 * so half a declaration is a fail-open and is refused exactly like none.
 *
 * That label is deliberately distinct from the opaque
 * "daemon-start-failed": a host must be able to route a roots refusal to
 * whatever screen collects the folders, and every other start failure to a
 * generic notice. tc_daemon_start takes no settings, so the only way out of
 * this refusal through this ABI is tc_daemon_start_with_settings below.
 *
 * NAMED START FAILURES. Every other way a start can fail also reports a
 * fixed, content-free label, so a host can tell them apart without parsing
 * prose:
 *
 *   "already-running"              another daemon holds this state
 *                                  directory's lock. Not an error to repair:
 *                                  the daemon the contributor wants is
 *                                  already up.
 *   "state-directory-not-writable" the lock file could not be created or
 *                                  opened. A permissions or disk problem
 *                                  with the state directory itself.
 *   "settings-unreadable"          daemon-settings.json exists and this
 *                                  version cannot parse it. Re-running
 *                                  whatever screen writes settings repairs
 *                                  it; hand-edited files are the usual
 *                                  cause.
 *   "ipc-bind-failed"              the control socket could not be bound.
 *                                  Most often a config_dir whose socket path
 *                                  exceeds the platform limit (see the
 *                                  104-byte note above), or a stale socket.
 *   "daemon-start-failed"          anything else, and deliberately opaque:
 *                                  the errors behind it embed filesystem
 *                                  paths that must not cross this boundary.
 *
 * These are the complete set; treat an unrecognized label as equivalent to
 * "daemon-start-failed" rather than assuming it is safe to display.
 *
 * SESSION SOURCE KEYS. Settings carry one declaration per agent, under
 * "claude_source" and "codex_source". Each is an object in one of exactly
 * two shapes:
 *
 *   {"mode":"watch","path":"/absolute/path/to/sessions"}
 *   {"mode":"off"}
 *
 * ABSENT IS NOT "off", AND CONFLATING THEM IS A FAIL-OPEN. A key that is
 * absent means the contributor has never been asked, and an unasked source
 * still falls back to the conventional per-user location -- the real
 * ~/.claude/projects or ~/.codex/sessions. {"mode":"off"} means they were
 * asked and declined, and nothing for that agent is watched or read. A host
 * that emits nothing to mean "the contributor does not use this agent" has
 * asked the daemon to watch that agent's real session store.
 *
 * "roots-not-declared" is refused on absence, never on {"mode":"off"}: a
 * contributor who declined both agents has declared their roots as surely as
 * one who named two folders.
 *
 * The legacy string spellings "claude_root" / "codex_root" still load and
 * are folded into the shapes above, then dropped the next time settings are
 * written, so an install that declared its roots before this schema existed
 * is not asked again. Emit the source keys; do not emit the legacy spellings
 * in new code.
 */
tc_handle*  tc_daemon_start(const char* config_dir, char** err);

/* Like tc_daemon_start, but applies settings_json -- a JSON object of
 * DaemonSettings fields -- BEFORE starting the daemon, so its first
 * supervisor tick (which fires immediately on start, not after the first
 * poll interval) already observes it. This is the ONLY way through this
 * ABI to set claude_root / codex_root before the daemon has already scanned
 * the previously-persisted (or default per-user) session roots once:
 * tc_call(handle, "set_settings", ...) only works on an already-running
 * daemon, by which point that first scan has already happened.
 *
 * settings_json accepts exactly the fields tc_call(handle, "set_settings",
 * ...) does: quiescence_secs, digest_interval_secs, approval_hold_secs,
 * local_notifications, claude_root, codex_root, max_uploads_per_day,
 * max_bytes_per_day -- one shared validation, so there is one
 * definition of "a valid settings object" for both entry points. An
 * unrecognized top-level key, or a recognized key holding the wrong JSON
 * type, is rejected with a fixed error label rather than silently ignored
 * -- silently ignoring a misspelled claude_root would leave the daemon
 * watching the wrong directory with no signal that anything was wrong.
 *
 * settings_json may be NULL, or empty (after trimming ASCII whitespace),
 * meaning "use whatever is currently persisted" -- identical to
 * tc_daemon_start. It is not otherwise optional: malformed JSON is a fixed
 * error label, never a panic.
 *
 * Returns NULL and sets *err (if err is non-NULL) on failure, exactly like
 * tc_daemon_start -- *err, on failure, is an owned string; free it with
 * tc_string_free. A settings_json problem reports one of its own fixed
 * labels (never settings_json's own text, since it is the one input here
 * that may itself contain a filesystem path); any other failure (a bad
 * config_dir, another daemon already holding the lock) reports the same
 * opaque "daemon-start-failed" tc_daemon_start does.
 *
 * The returned handle, on success, is exactly a tc_daemon_start handle --
 * every rule above about tc_daemon_start's return value, and everything
 * below about tc_daemon_stop / tc_handle_free, applies to it unchanged.
 *
 * FAILS CLOSED ON UNDECLARED SESSION ROOTS, on the same rule and with the
 * same "roots-not-declared" label as tc_daemon_start -- but evaluated AFTER
 * settings_json has been applied and persisted. That ordering is the point:
 * a settings_json declaring both roots clears a refusal the persisted file
 * alone would have earned, which is what makes this the one call a host can
 * use to turn "the contributor just named two folders" into a running
 * daemon. Declaring only one root here is refused exactly as it is above.
 */
tc_handle*  tc_daemon_start_with_settings(const char* config_dir, const char* settings_json, char** err);

/* Describe the session stores on this machine, so a roots screen can ask the
 * contributor about something specific rather than showing an empty field.
 *
 * Takes no handle: it runs BEFORE any daemon exists, which is the point --
 * the screen that uses it is the one clearing the refusal that stops a
 * daemon from starting.
 *
 * Returns an owned JSON array; free it with tc_string_free. Each element:
 *   source            "claude-code" | "codex"
 *   path              where this store would be watched
 *   exists            whether that directory is there right now
 *   session_count     how many session files, counted recursively
 *   most_recent       RFC 3339 timestamp, or null
 *   relocated_by_env  whether CLAUDE_CONFIG_DIR / CODEX_HOME moved it
 *
 * This is the ONE place in this ABI that deliberately returns a filesystem
 * path. Everywhere else a path is withheld because the caller is being told
 * about a trace; here the caller is the contributor's own machine asking
 * which of their own folders to watch, and a consent prompt that will not
 * name what it is asking about is not a consent prompt.
 *
 * Reads directory entries and metadata only; never opens a session file.
 * Returns NULL only on a caught panic.
 */
char*       tc_discover_sources(void);

/* Every fixed word on the routing surface, in one call.
 *
 * Takes no handle: it describes the build, not a running daemon.
 *
 * Returns an owned JSON object; free it with tc_string_free. Its keys are
 * tools_heading, word_private, word_direct, word_unknown, word_not_used,
 * tool_claude, tool_codex, tool_gemini, tool_cline, intro, toggle,
 * applies_at_once, port_title, port_note, folder_title, folder_note, apply,
 * checking, check_unavailable, probe_reachable, state_off, state_waiting
 * and state_reading. Every value is a non-empty string.
 *
 * All but one are fixed wording. folder_note names the folder this machine
 * reads when the folder field is left empty, because every failure sentence
 * on that surface ends by sending a contributor to that field, and a field
 * that will not say which folder it means is an instruction with no answer.
 * It is therefore the one value here that differs between machines, and the
 * one that can carry a filesystem path.
 *
 * ONE CALL, NOT ONE PER STRING. tc_scrub_detector_names answers a single
 * question and returns a single list; this is a whole screen's wording and
 * must arrive as a set. Exporting the words one at a time would let a shell
 * take four of them and hand-write the fifth, and a hand-written word on this
 * surface is a privacy claim that silently stops matching the one the other
 * two shells print.
 *
 * Exactly one of these words -- word_private -- claims privacy, and no word
 * denies one. Do not derive a "not private" label from any of the others:
 * "Private" is a substring of "Not private", and a shell that renders both is
 * one substring match away from showing the wrong verdict.
 *
 * Returns NULL only on a caught panic.
 */
char*       tc_routing_copy(void);

/* IronWire's answer about one tool, as tc_routing_tool_word and
 * tc_routing_tool_tone take it.
 *
 * Three states and not a boolean. The missing third state is the whole
 * defect this surface was rebuilt to remove: a dead proxy and a tool
 * IronWire has never heard of both used to render as a confident verdict.
 *
 * Any other value is TC_TOOL_WIRING_UNKNOWN, which claims nothing.
 */
#define TC_TOOL_WIRING_WIRED     0
#define TC_TOOL_WIRING_NOT_WIRED 1
#define TC_TOOL_WIRING_UNKNOWN   2

/* How a word or a state sentence is painted. tc_routing_tool_tone and
 * tc_routing_state_tone both answer one of these.
 *
 * ONE NUMBERING FOR BOTH. A tool word can never be HELD -- only a daemon
 * state waits on something -- but two numberings would mean two 1s meaning
 * different things on one ABI, and a shell that mapped the wrong one would
 * mispaint a privacy claim rather than fail.
 *
 * A tool word is never HELD or ATTENTION. ATTENTION is reachable only from
 * tc_routing_state_tone, and only for the one state that is asking somebody
 * to change something on this machine: declared, and no reader could be
 * built. It is not an alarm and not a fault verdict about anything remote --
 * it is the tone that stops "cannot read" being painted as "off" or as "all
 * fine". A shell that does not know it must not fall back to CLEAR.
 */
#define TC_ROUTING_TONE_NEUTRAL   0
#define TC_ROUTING_TONE_HELD      1
#define TC_ROUTING_TONE_CLEAR     2
#define TC_ROUTING_TONE_ATTENTION 3

/* One tool's word, from what the contributor said about that tool's sessions
 * and what IronWire said about that tool.
 *
 * source_mode is get_settings's *_source_mode -- "off", "watch" or "unset".
 * Only "off" means the tool is not used: "unset" watches the conventional
 * location, which is a tool in use. wiring is one of TC_TOOL_WIRING_*.
 *
 * THE BRANCH TABLE CROSSES, NOT ONLY THE WORDS. tc_routing_copy hands a shell
 * four words; without this call each shell also decides which of the four a
 * tool gets, and three native copies of that decision can drift apart
 * silently while every string stays identical. Do not reimplement this
 * mapping natively.
 *
 * The declaration switch is NOT an input. It was the only input before, and
 * that is what let a contributor read the wired word on the same card as
 * "Nothing answered on port 8463".
 *
 * Pair every call with tc_routing_tool_tone rather than comparing the word
 * this returns against the private one: "Private" is a substring of the
 * denial that must never come back.
 *
 * Returns an owned string; free it with tc_string_free. Returns NULL for a
 * NULL or non-UTF-8 source_mode, recording "null-pointer" or "invalid-utf8"
 * for tc_last_error.
 */
char*       tc_routing_tool_word(const char* source_mode, int32_t wiring);

/* How the word tc_routing_tool_word returned is painted: TC_TOOL_TONE_NEUTRAL
 * or TC_TOOL_TONE_CLEAR.
 *
 * Takes the same two inputs as the word, so the two stay in step by
 * construction. A shell must NOT recover this by comparing the rendered word
 * against the private one -- that is a text comparison against a privacy
 * claim, and "Private" is a substring of "Not private".
 *
 * Never fails: a NULL or non-UTF-8 source_mode, and a caught panic, all
 * answer TC_ROUTING_TONE_NEUTRAL, the tone that claims nothing. There is no
 * error value, because a styling call that returned one would leave a shell
 * choosing a tone for itself. A tool word is never TC_ROUTING_TONE_HELD.
 */
int32_t     tc_routing_tool_tone(const char* source_mode, int32_t wiring);

/* The daemon's routing state, in words.
 *
 * Exported for the same reason tc_routing_tool_word is: the sentences were
 * already shared, but the mapping from "awaiting_rows" / "rows_seen" /
 * anything-else onto them was written out again in each shell, and three
 * copies of a branch can disagree while three copies of a string cannot.
 *
 * A state this build has never heard of -- and a NULL or non-UTF-8 state --
 * reads as the off line, which claims nothing. It never falls through to
 * any of the three "on" sentences.
 *
 * "token_unreadable" is one of those three: the proxy is declared, and the
 * reader could not be built at all. It used to arrive here as the unknown
 * state and read as off, which told a contributor with the switch on that
 * the feature was off.
 *
 * Returns an owned string; free it with tc_string_free. NULL only on a caught
 * panic.
 */
char*       tc_routing_state_line(const char* state);

/* How firmly the sentence tc_routing_state_line returned reads:
 * TC_ROUTING_TONE_NEUTRAL, _HELD, _CLEAR or _ATTENTION.
 *
 * Exported for the reason the sentence is. This was the last routing branch
 * table still written out natively in all three shells, and three copies of
 * one decision agree today and drift apart in silence tomorrow.
 *
 * awaiting_rows is HELD and never a fault: a reader built a moment ago starts
 * empty by construction, and that is the state a contributor sees immediately
 * after touching anything on this card. Painting it as broken would accuse a
 * working proxy at exactly that moment.
 *
 * token_unreadable is ATTENTION, and it is the only state that reaches that
 * tone. It is neither NEUTRAL nor CLEAR on purpose: painted neutral it reads
 * as off, painted clear it reads as fine, and it is a state somebody has to
 * act on.
 *
 * Never fails. A state this build has never heard of, a NULL or non-UTF-8
 * state, and a caught panic all answer TC_ROUTING_TONE_NEUTRAL -- the same
 * fallback, for the same state, as tc_routing_state_line.
 */
int32_t     tc_routing_state_tone(const char* state);

/* The routing surface's "that file could not be used" sentence, assembled.
 *
 * token_path may be NULL, which is the case where nothing resolved at all;
 * the sentence for that says what to do instead of naming a file it does not
 * have.
 *
 * ASSEMBLED ON THE RUST SIDE, DELIBERATELY. This ABI does not export a
 * template with a hole in it, because a template each shell fills in is a
 * fourth, fifth and sixth place this wording lives, each free to drop a
 * clause around the hole, with nothing to notice when one does. Do not
 * reassemble these sentences from parts.
 *
 * Returns an owned string; free it with tc_string_free. NULL only on a caught
 * panic.
 */
char*       tc_routing_token_line(const char* token_path);

/* The routing surface's "nothing answered" sentence, assembled.
 *
 * port outside 1..65535 -- including the 0 a caller passes for "no port was
 * tried" -- produces the sentence that names no port, rather than one that
 * names a port number nobody used.
 *
 * Assembled on the Rust side, for the reason on tc_routing_token_line.
 *
 * Returns an owned string; free it with tc_string_free. NULL only on a caught
 * panic.
 */
char*       tc_routing_unreachable_line(int32_t port);

/* The routing surface's discovery sentence, assembled.
 *
 * port is what discover_routing reported, or 0 for a machine that published
 * no pointer. A port outside 1..65535 is treated as 0 -- the sentence for
 * "nothing was discovered", which names no port rather than naming one
 * nothing published.
 *
 * A MACHINE WITH NO POINTER IS NOT AN ERROR, and neither branch of this
 * sentence says otherwise. It is the ordinary state of a machine without
 * IronWire, and there is nothing here for a caller to handle: both branches
 * are a real sentence, and neither is a failure to render as one.
 *
 * Assembled on the Rust side, for the reason on tc_routing_token_line.
 *
 * Returns an owned string; free it with tc_string_free. NULL only on a caught
 * panic.
 */
char*       tc_routing_discovery_line(int32_t port);

/* The routing surface's "Last checked ..." sentence, assembled.
 *
 * when is the shell's own humanised time -- "an hour ago", "yesterday". That
 * is the one piece of this surface each shell renders for itself, because it
 * is a rendering of a timestamp and not wording about routing. The words
 * around it are still written once, on the Rust side.
 *
 * Returns NULL for a NULL or non-UTF-8 when, recording "null-pointer" or
 * "invalid-utf8" for tc_last_error: unlike the two sentences above there is
 * no meaningful shorter form of this one -- "Last checked " with nothing
 * after it is worse than no line at all -- and a shell with no timestamp
 * should not be calling it.
 *
 * Returns an owned string; free it with tc_string_free.
 */
char*       tc_routing_last_checked(const char* when);

/* The settings screen's session-source row for one tool, assembled.
 *
 * tool is "claude", "codex", "gemini" or "cline". source_mode is get_settings's
 * *_source_mode -- "watch", "off" or "unset".
 *
 * THREE MODES, THREE SENTENCES. *_root_configured is (mode == "watch") and is
 * therefore false for both "off" and "unset". A shell that branches on that
 * boolean tells a contributor who declared a tool OFF that their sessions are
 * being read from the usual place, which is false in the fail-open direction
 * on the one screen they would check to confirm otherwise. Call this with the
 * mode word and render what comes back; do not add a second branch of your
 * own, and do not build the "off" line as the "unset" line with a "not" in
 * front -- no word on this surface may deny a claim another word makes.
 *
 * Assembled on the Rust side, for the reason on tc_routing_token_line.
 *
 * "unset" is answered per tool, not once for everybody: an undeclared
 * "claude" or "codex" is scanned at its conventional location and its row says
 * sessions are read, while an undeclared "gemini" or "cline" constructs no
 * adapter and its row says nothing is opened. Render what comes back for the
 * tool you asked about; never carry one tool's "unset" sentence to another.
 *
 * A source_mode this build does not know renders as "unset", deliberately:
 * an older daemon sends no mode at all, and claiming nothing is read from a
 * folder that is being scanned is the worse of the two errors. An unknown
 * tool is refused, because there is no safe sentence for a tool with no name.
 *
 * Returns an owned string; free it with tc_string_free. NULL with
 * "unknown-source-tool", "null-pointer", "invalid-utf8" or "panic" recorded
 * for tc_last_error.
 */
char*       tc_source_check_line(const char* tool, const char* source_mode);

/* The names of the secret detectors the scrubber runs, so a shell can tell a
 * contributor what is removed without transcribing the list.
 *
 * Takes no handle: it describes the build, not a running daemon, and the
 * screen that asks is the first one a contributor sees.
 *
 * Returns an owned JSON array of strings; free it with tc_string_free.
 *
 * NAMES ONLY. The patterns are deliberately absent and must not be added: a
 * contributor deciding whether to trust the scrubbing needs to know what it
 * looks for, but publishing the regexes would tell someone trying to slip a
 * secret past it exactly what to avoid. The list being generated is the
 * point -- a hand-written copy in a shell is a privacy claim that silently
 * stops being true the day a detector is added.
 *
 * Returns NULL only on a caught panic.
 */
char*       tc_scrub_detector_names(void);


/* ---------------------------------------------------------------------------
 * The redaction witness
 * ---------------------------------------------------------------------------
 *
 * A redaction witness is an attested enclave that redacts a contributor's
 * raw session on their behalf and returns a signed certificate over the
 * result. Until these calls existed it was reachable only by hand-editing a
 * config file or setting three environment variables, so nobody running a
 * shipped app could turn it on, off, or even see whether it was on.
 *
 * THERE IS NO BOOLEAN HERE, AND THERE MUST NEVER BE ONE. "Is a witness
 * configured?" has two yes-answers that are opposites:
 *
 *   - PINNED: every submission goes through the enclave and comes back
 *     certified.
 *   - CONFIGURED BUT UNPINNED: every submission is REFUSED, before any
 *     network call, because a client with no pinned measurement cannot
 *     judge any quote it receives. Nothing uploads at all.
 *
 * An unpinned witness is a total upload outage, and a shell that renders it
 * the same as "no witness configured" tells a contributor everything is
 * fine while nothing works. tc_witness_trust_state is the one answer, with
 * one value per condition, and no other call in this header will collapse
 * them for you.
 *
 * Having NO witness is a legitimate, supported mode: local redaction runs
 * exactly as it does with this feature absent. It is not degraded and must
 * not be presented as a warning.
 */

/* No witness configured. Local redaction runs. NOT a warning state. */
#define TC_WITNESS_STATE_ABSENT                            0
/* Configured and pinned. Submissions go through the witness. */
#define TC_WITNESS_STATE_PINNED                            1
/* Configured, nothing pinned. EVERY SUBMISSION IS REFUSED. */
#define TC_WITNESS_STATE_REFUSING_UNPINNED                 2
/* Configured, pins unparsable. Also a total refusal -- and a different
 * mistake: a contributor who mistyped a measurement must not be told they
 * pinned none. */
#define TC_WITNESS_STATE_REFUSING_PIN_MALFORMED            3
/* Configured and pinned, refusing because a trace's inferences did not
 * carry verified receipts. RESERVED: no build returns it yet. It is
 * defined now so the attested-inference work can start returning it
 * without moving any other value, and so a shell written today already has
 * a branch for it. Its instruction to a contributor is not "pin a
 * measurement", which is why it is not folded into the value above. */
#define TC_WITNESS_STATE_REFUSING_INFERENCE_RECEIPTS_MISSING 4
/* Not enrolled: there is no config to hold a witness. NOT "absent" --
 * absent is a decision a contributor made. Not a refusal either: nothing
 * about a witness is being declined, the device has no account yet. */
#define TC_WITNESS_STATE_NOT_ENROLLED                     -1
/* The config could not be read. NOT "absent": a client whose behaviour is
 * unknown is not a client redacting locally, and nothing goes out from a
 * client that cannot read its own settings. A refusal. */
#define TC_WITNESS_STATE_UNREADABLE                       -2

/* The tones the witness surface is painted in. DELIBERATELY DISJOINT FROM
 * TC_ROUTING_TONE_*, which stops at ATTENTION = 3 and has no refused value.
 * Its consumers spell out their arms and map anything else to NEUTRAL, so
 * numbering a witness REFUSED as 4 would make a refusal render as "nothing
 * to say" in any shell that cross-wired the two mappers -- exactly the
 * failure this surface exists to prevent. A disjoint range makes that
 * mistake wrong for every value instead of only for the dangerous one.
 *
 * A TONE THIS HEADER DOES NOT DEFINE MUST BE RENDERED AS
 * TC_WITNESS_TONE_REFUSED, never as neutral. Every value added later is a
 * condition this build has no words for, and on a surface about whether
 * sessions leave the machine the safe reading of "I do not know" is "they
 * are not".
 */
#define TC_WITNESS_TONE_NEUTRAL   10
#define TC_WITNESS_TONE_HELD      11
#define TC_WITNESS_TONE_CLEAR     12
#define TC_WITNESS_TONE_ATTENTION 13
#define TC_WITNESS_TONE_REFUSED   14

/* What the witness is doing, as one of the TC_WITNESS_STATE_* values above.
 *
 * The one call to make before rendering anything about the witness.
 *
 * A VALUE THIS HEADER DOES NOT DEFINE MUST BE RENDERED AS "not usable",
 * NEVER AS TC_WITNESS_STATE_ABSENT. A shell built against this header may
 * run against a later library that has learned a new refusal, and
 * defaulting an unknown state to "no witness, all is well" turns a future
 * refusal into silence.
 *
 * Needs no handle: it reads the config file, and the screen that calls it
 * is often the one deciding whether to start a daemon at all. Records a
 * fixed tc_last_error label for the two negative values.
 */
int32_t     tc_witness_trust_state(const char* config_dir);

/* The whole witness configuration, as an OWNED JSON object; free it with
 * tc_string_free:
 *
 *   {"state":"refusing_unpinned","state_code":2,
 *    "refusal":"witness_expected_measurement",
 *    "url":"https://witness.example","signing_address":"0x...",
 *    "pinned_measurement_count":0,
 *    "pinned_measurement_line":"No measurement is pinned.",
 *    "pinned_measurements":[]}
 *
 * pinned_measurements is the pinned sets VERBATIM, in stored order, and is
 * exactly what tc_witness_configure takes as measurements_json: pre-fill the
 * editor from it and hand it straight back. Do NOT re-serialise it from a
 * parsed measurement -- a shell that reformats a pin is a shell that can
 * reformat it wrongly. Its length is always pinned_measurement_count.
 *
 * A stored entry this build cannot parse is returned AS IT IS STORED, not
 * omitted: the state is already refusing_pin_malformed, and the entry is
 * there so a contributor can see the typo and fix it. Omitting it would
 * delete their work the next time they saved.
 *
 * Because the editor can be pre-filled, an EMPTY measurements box genuinely
 * means the contributor cleared it, and tc_witness_configure is right to
 * refuse it with "witness-pin-required". There is no "keep what is there"
 * mode and there must not be one: it would save a pin nobody looked at.
 *
 * pinned_measurement_line is the sentence for that count, or null when there
 * is no witness to count for. Print it rather than a bare numeral, and do
 * not write your own.
 *
 * state and state_code are the same answer tc_witness_trust_state gives.
 * DO NOT DERIVE THE STATE FROM url BEING NON-NULL -- that is the boolean
 * this surface refuses to hand you, spelled differently. refusal is null
 * unless the state is a refusing one.
 *
 * THE URL AND SIGNING ADDRESS ARE RETURNED VERBATIM, one of the three
 * exemptions named at the top of this header. They are the contributor's
 * own configuration, not a value derived from a session, and a screen that
 * will not show what it is asking a contributor to trust with their raw
 * session is not a settings screen. Nothing else about the witness path --
 * no quote, no signature, no certificate body -- crosses this boundary.
 *
 * Returns NULL and sets *err (owned; free with tc_string_free) when the
 * device is not enrolled or the config cannot be read. A NULL return is
 * never "no witness": that is state "absent" on a successful call.
 */
char*       tc_witness_status_json(const char* config_dir, char** err);

/* Configure a witness. Returns 0 on success, -1 on failure with *err set
 * (owned; free with tc_string_free).
 *
 * measurements_json is a JSON array of strings, each one measurement set in
 * the spelling "mrtd=<hex>,mrconfigid=<hex>". It is a LIST because an image
 * upgrade moves the measurement and leaves the signing address where it is:
 * an operator adds the new measurement before the fleet rolls, and a client
 * holding only the old one refuses the new deployment.
 *
 * THIS CALL WILL NOT WRITE AN UNPINNED WITNESS. An empty array is refused
 * with "witness-pin-required" and an unparsable one with
 * "witness-pin-malformed", because either produces a client that refuses
 * every submission from the moment it is saved. The read side still reports
 * both states, since a hand-edited file or the TRACE_COMMONS_WITNESS_*
 * environment variables can still create them; this ABI simply declines to
 * be the thing that does.
 *
 * Other fixed labels: "witness-not-enrolled", "witness-config-unreadable",
 * "witness-url-invalid", "witness-signing-address-invalid",
 * "witness-pins-invalid-json", "witness-config-write-failed".
 *
 * Takes effect on the next submission -- the upload path reloads the config
 * per upload -- with no daemon restart. An entry already previewed and
 * approved is re-offered rather than uploaded, because turning a witness on
 * changes who builds the envelope and therefore what bytes a contributor is
 * approving.
 */
int32_t     tc_witness_configure(const char* config_dir, const char* url,
                                 const char* signing_address,
                                 const char* measurements_json, char** err);

/* Remove the configured witness. Returns 1 if one was removed, 0 if there
 * was none, -1 on failure with *err set (owned; free with tc_string_free).
 *
 * Clearing returns the client to LOCAL REDACTION, a supported mode rather
 * than a broken one. It is still a real change: later submissions carry a
 * self-reported residual-risk verdict rather than a certified one, so say
 * what is happening rather than presenting this as switching off a setting.
 *
 * Idempotent: clearing a witness that is not there is 0, not an error.
 */
int32_t     tc_witness_clear(const char* config_dir, char** err);

/* What the last submission THIS PROCESS made did about the witness, as an
 * OWNED JSON object; free it with tc_string_free:
 *
 *   {"outcome":"certified","certificate_obtained":true,
 *    "certificate_verified":true,"refusal":null,"n_of_m":{"n":3,"m":7}}
 *
 * outcome is one of:
 *   "not_observed"    -- this process has made no submission. Say nothing
 *                        about the last one rather than guessing.
 *   "local_redaction" -- built locally because no witness was configured.
 *                        Expected; NOT a missing certificate.
 *   "certified"       -- a certificate was obtained AND verified against
 *                        the bytes the witness returned. There is no path
 *                        to this value that skipped the verification.
 *   "refused"         -- refusal carries the fixed label, and
 *                        certificate_obtained separates a witness that
 *                        answered with a certificate that does not hold
 *                        from one that never answered.
 *
 * Every key is present in every outcome, so a shell never has to decide
 * what an absent key meant.
 *
 * n_of_m is null unless the certificate carried a count of how many of a
 * trace's inferences carried a verified receipt, out of how many the trace
 * had. It is null on every certificate this build has seen; the field is
 * here so the attested-inference work needs no ABI change. WHEN PRESENT,
 * RENDER IT AS THE PAIR. There is no "attested" boolean to derive from it
 * and one must not be invented: a certificate attests mechanics and a
 * verdict, never that a trace is clean.
 *
 * PROCESS-LOCAL, DELIBERATELY. Nothing is written to disk, because a file
 * would outlive a logout and show the next contributor to enroll on this
 * machine the previous one's submission outcome. A freshly started shell
 * reports "not_observed" until it makes a submission.
 *
 * Needs no handle. Returns NULL only on a caught panic.
 */
char*       tc_witness_last_result_json(void);

/* Every fixed word on the witness surface, in one call. Returns an OWNED
 * JSON object whose keys are heading, intro, certificate_means,
 * measurements_note, url_title, signing_address_title, measurements_title,
 * configure, clear, clear_note, applies_at_once; free with tc_string_free.
 *
 * ONE CALL, NOT ONE PER STRING, and NOT A WORD OF YOUR OWN. A shell handed
 * the words one at a time takes some of them and writes the rest, and a
 * hand-written word here is a privacy claim that stops matching what the
 * other shells print. Every string on this surface comes from the Rust core,
 * which is also where GTK -- which does not use this ABI at all -- reads
 * them from.
 *
 * Returns NULL only on a caught panic.
 */
char*       tc_witness_copy(void);

/* The sentence for a witness state, given a TC_WITNESS_STATE_* value.
 * Returns an OWNED string; free with tc_string_free.
 *
 * Returns NULL, recording the fixed tc_last_error label
 * "witness-state-unknown", for a value this build cannot name. A shell that
 * gets NULL must render NO witness sentence rather than one of its own, and
 * should pair that with tc_witness_state_tone, which fails closed to
 * TC_WITNESS_TONE_REFUSED on the same input.
 */
char*       tc_witness_state_line(int32_t state_code);

/* The tone tc_witness_state_line's sentence is painted in, as a
 * TC_WITNESS_TONE_* value.
 *
 * ONE BRANCH TABLE, NOT TWO: this takes what the sentence takes. Do not
 * recover the tone by comparing the rendered sentence against anything.
 *
 * A state this build cannot name is TC_WITNESS_TONE_REFUSED, NOT neutral --
 * the fail-closed direction, deliberately.
 */
int32_t     tc_witness_state_tone(int32_t state_code);

/* The sentence for what the last submission THIS PROCESS made did about the
 * witness. Returns an OWNED string; free with tc_string_free.
 *
 * The prose form of tc_witness_last_result_json, and THE ONLY FORM A SHELL
 * MAY PRINT: that call's "refusal" is a fixed operator label rather than
 * wording, and its n_of_m is a pair a shell must not phrase itself. When a
 * certificate carried a count this sentence already contains it, as "3 of 7
 * model calls carried a receipt." -- never the word "attested", and never a
 * claim that a session is clean.
 *
 * Returns NULL only on a caught panic.
 */
char*       tc_witness_last_result_line(void);

/* The tone tc_witness_last_result_line's sentence is painted in, as a
 * TC_WITNESS_TONE_* value. A refused send is TC_WITNESS_TONE_REFUSED and
 * never ATTENTION: nothing was sent at all, which is not a
 * degraded-but-working state.
 */
int32_t     tc_witness_last_result_tone(void);


/* Stop the daemon loop. Idempotent, and safe to call from any thread --
 * including from inside a tc_subscribe callback -- and safe to call
 * concurrently with tc_call / tc_preview_open / tc_subscribe on other
 * threads. Does NOT free the handle; call tc_handle_free once nothing else
 * will use it again. Safe to call with NULL.
 *
 * Idempotent, but NOT a teardown barrier for a second concurrent caller:
 * of two simultaneous callers, one performs the teardown and the other
 * returns immediately, possibly before the daemon has finished stopping.
 * And do NOT call tc_handle_free concurrently with this function. Both
 * rules, and why, are spelled out at the top of this header.
 *
 * Is NOT a synchronization point for tc_subscribe callbacks -- see
 * SUBSCRIPTION LIFETIME above and tc_unsubscribe below.
 *
 * A handle that is not currently a live tc_handle* -- already freed by
 * tc_handle_free, or a tc_preview* passed here by mistake -- is refused
 * before any dereference: returns immediately, recording the fixed
 * tc_last_error label "invalid-handle-pointer".
 */
void        tc_daemon_stop(tc_handle*);

/* Free a handle. The only function that reclaims what tc_daemon_start
 * returned; tears the daemon down first if tc_daemon_stop was not already
 * called. Safe to call with NULL.
 *
 * MUST be called from a plain thread that is not inside any tokio runtime
 * context -- in particular, never from inside a tc_subscribe callback.
 * handle owns its own async runtime; freeing it from one of that runtime's
 * own worker threads is refused (leaking the handle, recorded via
 * tc_last_error) rather than risking the crash that would otherwise
 * follow.
 */
void        tc_handle_free(tc_handle*);

/* Control. Same request handlers the socket serves, called in-process.
 *
 * Returns a NUL-terminated JSON response; free with tc_string_free. Never
 * returns NULL: a bad handle, method, or params_json produces a JSON error
 * frame (`{"error":{"code":"bad_params",...}}`) rather than a null pointer.
 *
 * A non-NULL handle that is not a live tc_handle* -- already freed, or a
 * tc_preview* passed here by mistake -- is refused the same way: a JSON
 * error frame (bad_params / "invalid-handle-pointer") rather than a
 * dereference of a pointer whose type cannot be trusted.
 *
 * tc_call(h, "shutdown", "{}") stops the daemon loop. It is equivalent to
 * tc_daemon_stop for the daemon's own state -- afterwards every call on
 * this handle reports `{"error":{"code":"unavailable","message":
 * "daemon-stopped"}}` and tc_subscribe returns 0 -- but it does NOT
 * release the state directory or the handle's resources. Call
 * tc_daemon_stop and then tc_handle_free to do that.
 */
char*       tc_call(tc_handle*, const char* method, const char* params_json);

/* Events. cb is invoked on a background thread with a JSON event frame
 * each time the daemon publishes one, until tc_unsubscribe is called with
 * the returned token. The event_json pointer passed to cb is borrowed for
 * the duration of that one call only; do not retain it. ctx is passed back
 * unchanged and MUST remain valid until tc_unsubscribe returns -- full
 * stop; see SUBSCRIPTION LIFETIME above. tc_daemon_stop returning is NOT
 * sufficient.
 *
 * A gap in delivery (more than 256 events published between polls) is
 * reported to cb as a synthetic `{"event":"lagged","data":{"skipped":N}}`
 * frame rather than silently dropped.
 *
 * Returns 0 on failure -- 0 is never a valid token. On success, returns
 * a nonzero token for tc_unsubscribe.
 *
 * Every zero return records a fixed tc_last_error label, so "token == 0,
 * read tc_last_error" is a total contract: "null-handle",
 * "invalid-handle-pointer" (not a live tc_handle*), "null-callback", or
 * "daemon-not-running".
 */
uint64_t    tc_subscribe(tc_handle*, void (*cb)(const char* event_json, void* ctx), void* ctx);

/* Cancel a subscription returned by tc_subscribe. Blocks until that
 * subscription's callback is guaranteed to no longer fire before
 * returning -- see SUBSCRIPTION LIFETIME above; this is the only function
 * with that guarantee. A no-op if token is 0 or unknown.
 *
 * Also a no-op, recording the fixed tc_last_error label
 * "invalid-handle-pointer", if handle is non-null but not a live
 * tc_handle* -- refused before any dereference, the same as every other
 * entry point in this file.
 *
 * MUST be called from a plain thread that is not inside any tokio runtime
 * context -- in particular, never from a subscription's own callback
 * unsubscribing itself: that would block joining a task that can only
 * finish once the very callback frame making the call returns, a permanent
 * hang. Calling from inside a runtime context refuses (a no-op; the token
 * remains valid to retry from a plain thread) and records why via
 * tc_last_error.
 *
 * IMPORTANT for binding authors: that reentrancy check is "am I inside ANY
 * tokio runtime context", which cannot distinguish true reentrancy (a
 * callback unsubscribing itself) from a host that merely happens to call
 * tc_unsubscribe from a thread driving its own, unrelated async runtime.
 * The latter is refused too -- and because this function returns void, the
 * refusal is SILENT. A host that assumes success there would free ctx while
 * the subscription is still live, believing the API's only barrier had
 * held. Therefore: after every tc_unsubscribe, check tc_last_error. A
 * non-NULL, non-stale value means the call was refused and the barrier did
 * NOT hold -- retry from a plain thread with no runtime context before
 * freeing ctx. Clear or note the prior tc_last_error value first so a
 * leftover error is not mistaken for this one.
 */
void        tc_unsubscribe(tc_handle*, uint64_t token);

/* Preview. Reads the session file and runs the real redaction pipeline.
 *
 * tc_preview_open returns NULL and sets *err (if err is non-NULL) on
 * failure -- most commonly an unknown entry_id, or (deliberately) a
 * redacted body that cannot be represented as a NUL-terminated C string.
 * On success, everything returned by the tc_preview_* accessors below is
 * borrowed and valid until tc_preview_free.
 *
 * A non-NULL handle that is not a live tc_handle* is refused the same
 * way, before any dereference: NULL plus *err set to the fixed label
 * "invalid-handle-pointer".
 *
 * Safe to call from inside a tc_subscribe callback -- the natural flow of
 * receiving queue_changed and opening the preview for what changed. It
 * blocks the calling thread for the duration of the redaction pass, so a
 * host that must keep its callback short should hand the entry_id to its
 * own thread instead.
 */
tc_preview* tc_preview_open(tc_handle*, const char* entry_id, char** err);
const char* tc_preview_body(const tc_preview*);          /* redacted transcript, UTF-8 */
const char* tc_preview_summary_json(const tc_preview*);  /* counts, sizes, opening prompt */

/* Search the redacted body for needle, a local in-memory scan. Matches are
 * non-overlapping, left-to-right, and reported as UTF-8 BYTE offsets (not
 * character offsets). An empty needle matches nothing.
 *
 * Returns the number of matches, or -1 on error (including a match count
 * that would overflow a 32-bit count -- reported as an error, never
 * silently truncated). On success, *matches_json is set to an owned JSON
 * array of byte offsets; free with tc_string_free. On error, *matches_json
 * (if non-NULL) is set to NULL -- there is nothing to free.
 */
int32_t     tc_preview_search(const tc_preview*, const char* needle, char** matches_json);

/* Count occurrences of needle in an entry's PRE-redaction session text.
 * Returns the match count, or -1 on error. Reports a COUNT ONLY: no
 * offsets, no context, no bytes.
 *
 * This is the one call here that reads unredacted session bytes on behalf
 * of a caller, and the count is the bound. It exists because
 * tc_preview_search scans the REDACTED body, so a value redaction removed
 * returns zero there, which is indistinguishable from a value that was
 * never present.
 *
 * Takes a handle and an entry id, not a tc_preview*: a preview must not
 * hold pre-redaction bytes for as long as a sheet is open. The daemon
 * reads the file, counts, and drops it.
 */
int32_t     tc_search_original(tc_handle*, const char* entry_id, const char* needle);

/* The turn index over a redacted preview body:
 *   {entry_id, body_digest, envelope_digest, turn_count,
 *    turns: [{index, role, tool_name, byte_offset, byte_len}]}
 *
 * An OVERLAY on the body, never a replacement for it. Render the bytes
 * tc_preview_body returned verbatim and draw a separator at each
 * byte_offset; the offsets index that exact string. The daemon does not
 * re-render the transcript, because a prose re-render would drop the fields
 * that have no prose form (structured_payload, token_counts, latency_ms,
 * cost_usd, failure_modes) and so would show less than the artifact an
 * approval covers.
 *
 * body_digest is required and is the anchor: "sha256:<lowercase hex>" over
 * the exact UTF-8 bytes of the body being displayed. A body that is not
 * that one is refused with preview-body-changed rather than indexed --
 * offsets against the wrong string still look like a transcript.
 *
 * Returns an OWNED JSON string; free with tc_string_free. Returns NULL and
 * sets *err (owned; also freed with tc_string_free) on failure.
 *
 * A non-NULL handle that is not a live tc_handle* is refused the same
 * way, before any dereference: NULL plus *err set to the fixed label
 * "invalid-handle-pointer".
 */
char*       tc_preview_turns_json(tc_handle*, const char* entry_id,
                                  const char* body_digest, char** err);

/* The instance an invite link names, as an owned UTF-8 string, or NULL if
 * the argument is not a usable invite.
 *
 * Exists so a shell can resolve and show the instance before a contributor
 * commits to an invite, WITHOUT being handed the invite's code. The parsed
 * invite carries that code; only the host crosses this boundary, and a shell
 * cannot leak what it was never given.
 *
 * NULL covers every rejection. A caller must not try to distinguish "not a
 * URL" from "no code in it" -- this interface deliberately does not tell the
 * two apart, matching the single failure sentence the invite path shows.
 *
 * Not a daemon method: it is a pure function of its argument, touches no
 * daemon state, and needs no handle. Returns an OWNED string; free it with
 * tc_string_free.
 */
char*       tc_invite_issuer_host(const char* invite);

/* Free a preview handle. Safe to call with NULL. Invalidates every
 * const char* previously returned by tc_preview_body /
 * tc_preview_summary_json for this handle.
 */
void        tc_preview_free(tc_preview*);

/* Free a string returned by this library. Safe to call with NULL. This is
 * the only valid way to free a char* this library returns.
 */
void        tc_string_free(char*);

/* The last error recorded on the calling thread, or NULL if none has been
 * recorded yet. Borrowed: valid until the next call, on this same thread,
 * to any function in this library that records a new error. Do not free
 * the returned pointer.
 */
const char* tc_last_error(void);

#ifdef __cplusplus
}
#endif

#endif /* TRACE_COMMONS_H */
